#include "token.h"
#include "command.h"

//return token count
int tokenise(char* inputLine, char* token[]){
	int tokenCount = 0;
	
	//use strtok to get the first token in the string
	char* startToken = strtok(inputLine, " \t\n");

	//if string is empty 
	if (startToken == NULL) return 0;

	//allocate size for first token
	token[tokenCount] = malloc(sizeof(char) * strlen(startToken));
	strcpy(token[tokenCount], startToken);

	//loop through all the tokens generated by strtok
	while (startToken != NULL){
		if (tokenCount>MAX_NUM_TOKENS) return -1;
		
		tokenCount++;		
		startToken = strtok(NULL, " \t\n");

		//strtok returns NULL where there are no more tokens, make sure not to malloc in that case
		if (startToken!=NULL) {
			token[tokenCount] = malloc(sizeof(char) * strlen(startToken));
			strcpy(token[tokenCount], startToken);
		} else {
			token[tokenCount] = NULL;
		}
	}
	

	return tokenCount;
}
